// Generated by https://quicktype.io

export interface Elements {
    title:   string[];
    details: Detail[];
    contact: Contact;
    address: Address;
}

export interface Address {
    street:  string;
    city:    string;
    zipCode: string;
}

export interface Contact {
    name:  string;
    phone: string;
}

export interface Detail {
    name:  string;
    value: number | string;
}
